<?xml version="1.0" encoding='utf-8'?>
<xsl:stylesheet version="1.0" 
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:g="http://purl.org/openorg/grinder/ns/"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:gr="http://purl.org/goodrelations/v1#"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
    xmlns:spatialrelations="http://data.ordnancesurvey.co.uk/ontology/spatialrelations/"
    xmlns:soton="http://id.southampton.ac.uk/ns/"
    xmlns:oo="http://purl.org/openorg/"
    xmlns:aiiso="http://purl.org/vocab/aiiso/schema#"
    xmlns:skos="http://www.w3.org/2004/02/skos/core#"
    xmlns:dcterms="http://purl.org/dc/terms/"
>

<!-- note to self... use rapper to remove duplicate triples -->

  <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes" omit-xml-declaration="no" />

  <xsl:variable name='base-module-uri' select='/g:grinder-data/g:set[@id="base-module-uri"]' />
  <xsl:variable name='base-course-uri' select='/g:grinder-data/g:set[@id="base-course-uri"]' />
  <xsl:variable name='license-uri' select='/g:grinder-data/g:set[@id="license-uri"]' />
  <xsl:variable name='_timestamp' select='/g:grinder-data/g:set[@id="_timestamp"]' />

  <xsl:template match="/g:grinder-data">
    <rdf:RDF>

      <rdf:Description rdf:about=''>
        <xsl:if test="$license-uri != ''">
          <dcterms:license rdf:resource="{$license-uri}" />
        </xsl:if>
        <dcterms:title>University of Southampton Courses</dcterms:title>
        <rdfs:comment>Generated by OpenOrg Grinder using the banner.xsl by Christopher Gutteridge. See http://wiki.openorg.ecs.soton.ac.uk/index.php/OpenOrg_Grinder. Generated at <xsl:value-of select='$_timestamp' /></rdfs:comment>
 
      </rdf:Description>

      <xsl:comment>TOP</xsl:comment>
      <xsl:apply-templates select="g:row" /> 
    </rdf:RDF>
  </xsl:template>

<!--
	<csta-code>S</csta-code>
	<billing-hours-sum>5</billing-hours-sum>
	<gmod-code>G</gmod-code>
	<ptrm-start-date>30-Sep-10</ptrm-start-date>
	<ptrm-end-date>29-Jan-11</ptrm-end-date>
	<attr-code1>NQF7</attr-code1>
	<schd-code1>NULL</schd-code1>
	<instructor1-full-name>NULL</instructor1-full-name>
-->
  <xsl:template match="g:row">
    <aiiso:Module rdf:about="{$base-course-uri}{g:crn-key}/2010-2011">
      <rdfs:label><xsl:value-of select="g:subj-code" /><xsl:value-of select="g:crse-number" />: <xsl:value-of select="g:long-title" /> (<xsl:value-of select="g:ptrm-desc" />)</rdfs:label>
      <aiiso:name><xsl:value-of select="g:long-title" /></aiiso:name>
      <soton:BannerCrnKey><xsl:value-of select="g:crn-key" /></soton:BannerCrnKey>
      <soton:BannerCollCode><xsl:value-of select="g:coll-code" /></soton:BannerCollCode>
      <soton:BannerLevlCode1><xsl:value-of select="g:levl-code1" /></soton:BannerLevlCode1>
      <soton:BannerSubjCode><xsl:value-of select="g:subj-code" /></soton:BannerSubjCode>
      <soton:BannerPtrmCode><xsl:value-of select="g:ptrm-code" /></soton:BannerPtrmCode>
      <soton:BannerCrseNumber><xsl:value-of select="g:crse-number" /></soton:BannerCrseNumber>
      <soton:BannerCreditHoursSum><xsl:value-of select="g:credit-hours-sum" /></soton:BannerCreditHoursSum>
    </aiiso:Module>
    <soton:ModuleInSyllabus rdf:about="{$base-module-uri}{g:subj-code}{g:crse-number}/2010-2011">
      <rdfs:label><xsl:value-of select="g:subj-code" /><xsl:value-of select="g:crse-number" />: <xsl:value-of select="g:long-title" /> (2010-2011 session)</rdfs:label>
      <aiiso:name><xsl:value-of select="g:long-title" /></aiiso:name>
      <soton:BannerCrnKey><xsl:value-of select="g:crn-key" /></soton:BannerCrnKey>
      <soton:BannerCollCode><xsl:value-of select="g:coll-code" /></soton:BannerCollCode>
      <soton:BannerLevlCode1><xsl:value-of select="g:levl-code1" /></soton:BannerLevlCode1>
      <soton:BannerSubjCode><xsl:value-of select="g:subj-code" /></soton:BannerSubjCode>
      <soton:BannerPtrmCode><xsl:value-of select="g:ptrm-code" /></soton:BannerPtrmCode>
      <soton:BannerCrseNumber><xsl:value-of select="g:crse-number" /></soton:BannerCrseNumber>
      <soton:BannerCreditHoursSum><xsl:value-of select="g:credit-hours-sum" /></soton:BannerCreditHoursSum>
      <soton:moduleTaughtAs rdf:resource="{$base-course-uri}{g:crn-key}/2010-2011" />
    </soton:ModuleInSyllabus>


  </xsl:template>

  <xsl:template match="*" priority="-1">
     <!--<xsl:value-of select="concat( name(.), ':', string(.) )" />-->
  </xsl:template>

</xsl:stylesheet>
